Repository hivesolutions/yonius, pull requests merged in 2021-01, with the labels that each got.

#22 Validation and error types
  types/base/error.d.ts
  types/base/index.d.ts
  types/util/index.d.ts
  types/util/validation.d.ts
Labels: bug

#24 Type definitions for the HTTP basic methods from yonius
  types/api/api.d.ts
  types/api/index.d.ts
  types/index.d.ts
Labels: enhancement

#26 feat: new string validations
  js/util/validation.js
  test/util/validation.js
  types/base/main.d.ts
  types/data/model.d.ts
  types/util/assert.d.ts
  types/util/config.d.ts
  types/util/data.d.ts
  types/util/validation.d.ts
Labels: enhancement, p-medium
